In [2]:
import numpy as np

# creating numpy arrays

# np.array()

In [6]:
list1=[1,2,3,4,5]
array1=np.array(list1)
print(array1)
print(type(array1))
print(array1.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [7]:
lis=[[1,2],[3,4]]
array=np.array(lis)
print(array)
print(type(array))
print(array.ndim)

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
2


# np.zeros()

In [8]:
arrays=np.zeros(5)
print(arrays)

[0. 0. 0. 0. 0.]


In [9]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [11]:
np.zeros((1,2))

array([[0., 0.]])

# np.ones()

In [12]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

# np.full()

In [15]:
np.full(5,2)

array([2, 2, 2, 2, 2])

In [16]:
np.full((2,3),2)

array([[2, 2, 2],
       [2, 2, 2]])

In [17]:
np.full((2,3,4),5)

array([[[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]],

       [[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]]])

# np.arange()

In [18]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [19]:
np.arange(2,6)

array([2, 3, 4, 5])

In [20]:
np.arange(2,10,2)

array([2, 4, 6, 8])

# np.linspace()

In [21]:
np.linspace(1,10,2)

array([ 1., 10.])

In [22]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [23]:
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

In [24]:
np.linspace((2,4),(4,10),5)

array([[ 2. ,  4. ],
       [ 2.5,  5.5],
       [ 3. ,  7. ],
       [ 3.5,  8.5],
       [ 4. , 10. ]])

In [25]:
np.linspace((1,5),(4,10), num=5)

array([[ 1.  ,  5.  ],
       [ 1.75,  6.25],
       [ 2.5 ,  7.5 ],
       [ 3.25,  8.75],
       [ 4.  , 10.  ]])

In [26]:
np.linspace((1,5,6),(4,10,12), num=5)

array([[ 1.  ,  5.  ,  6.  ],
       [ 1.75,  6.25,  7.5 ],
       [ 2.5 ,  7.5 ,  9.  ],
       [ 3.25,  8.75, 10.5 ],
       [ 4.  , 10.  , 12.  ]])

# np.diag()

In [27]:
np.diag([2,3,4])

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 4]])

In [28]:
np.diag([2,3,4],k=1)

array([[0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4],
       [0, 0, 0, 0]])

In [29]:
np.diag([2,3,4],k=-1)

array([[0, 0, 0, 0],
       [2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0]])

# np.eye()

In [30]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
np.eye(5,k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [32]:
np.eye(5,k=1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

# np.identity()

In [33]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# np.random.rand()

In [34]:
np.random.rand(2,3)

array([[0.01527843, 0.53145868, 0.83310673],
       [0.0658693 , 0.15428857, 0.98365568]])

In [35]:
np.random.rand(4,4)

array([[0.0156125 , 0.42423481, 0.4512166 , 0.00094766],
       [0.32468427, 0.13877551, 0.8765478 , 0.00394936],
       [0.6983634 , 0.90719568, 0.81216644, 0.8356085 ],
       [0.60094211, 0.55096476, 0.29874006, 0.03686037]])

In [36]:
np.random.rand(2,3,4)

array([[[0.40442053, 0.79137964, 0.41918023, 0.74591129],
        [0.26898846, 0.71348742, 0.1704369 , 0.74458971],
        [0.48844684, 0.26741472, 0.64190878, 0.946146  ]],

       [[0.69373847, 0.58669311, 0.77995622, 0.1595103 ],
        [0.1148709 , 0.03456348, 0.84324986, 0.90978473],
        [0.99069043, 0.28763948, 0.10297999, 0.81588119]]])

In [37]:
np.random.randint(1,10,(4,4))

array([[4, 5, 5, 4],
       [6, 4, 1, 2],
       [5, 4, 6, 3],
       [9, 1, 4, 5]])

In [38]:
np.random.randint(1,5,(3,3))

array([[4, 2, 3],
       [3, 4, 2],
       [4, 2, 2]])

# Indexing numpy-arrays

In [39]:
arr=np.array([1,2,3,4,5])

In [40]:
arr[3]

4

In [41]:
arr[2]

3

In [42]:
arr

array([1, 2, 3, 4, 5])

In [43]:
list1=[[1,2,3],[4,5,6],[7,8,9]]

In [44]:
arr1=np.array(list1)

In [45]:
arr1[0][1]

2

In [46]:
arr1[0,1]

2

In [47]:
arr2=np.array([[[1,2],[3,4]],[[5,6],[6,7]]])

In [48]:
arr2[0]

array([[1, 2],
       [3, 4]])

In [49]:
arr2[0][1]

array([3, 4])

In [50]:
arr2[1][0][1]

6

# Numpy-array-slicing

In [51]:
li=[1,2,3,4,5]

In [52]:
li[0:4]

[1, 2, 3, 4]

In [53]:
arr3=np.array(li)

In [54]:
arr3[1:4]

array([2, 3, 4])

In [55]:
arrray=[1,2,3,4,5,6,7,8,9,10,11,12]

In [56]:
array=np.array(arrray)

In [57]:
array[3:10:2]

array([ 4,  6,  8, 10])

In [58]:
lis2=[[1,2,3,4,5,6],[7,8,9,10,11,12]]

In [59]:
lis2[0][3:6]

[4, 5, 6]

In [60]:
arr2=np.array(lis2)

In [61]:
arr2[0][3:]

array([4, 5, 6])

In [62]:
arr2[0,3:]

array([4, 5, 6])

In [63]:
arr2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [64]:
arr2[:,1:4]

array([[ 2,  3,  4],
       [ 8,  9, 10]])

In [66]:
arr2[:,1::2]

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [81]:
arr3=[[[1,2,3,4],[5,6,7,8]],[[7,8,9,10],[10,11,12,13]],[[13,14,15,16],[16,17,18,19]]]

arr3

In [82]:
arr3

[[[1, 2, 3, 4], [5, 6, 7, 8]],
 [[7, 8, 9, 10], [10, 11, 12, 13]],
 [[13, 14, 15, 16], [16, 17, 18, 19]]]

In [83]:
arr3[0]

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [84]:
arr4=np.array(arr3)

In [85]:
arr4

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 7,  8,  9, 10],
        [10, 11, 12, 13]],

       [[13, 14, 15, 16],
        [16, 17, 18, 19]]])

In [86]:
arr4[0]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [91]:
arr4[:,:1,1:5]

array([[[ 2,  3,  4]],

       [[ 8,  9, 10]],

       [[14, 15, 16]]])

# Numpy-method and attribute

In [94]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [109]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [95]:
a.shape

(2, 5)

In [97]:
a.dtype

dtype('int32')

In [98]:
a.ndim

2

In [99]:
a.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [100]:
a.sum()

55

In [101]:
a[0].sum()

15

In [102]:
a.max()

10

In [103]:
a[1].max()

10

In [104]:
a[0].max()

5

In [105]:
a.min()

1

In [106]:
a[1].min()

6

In [107]:
a.max(axis=0) #return maximum element of each column

array([ 6,  7,  8,  9, 10])

In [108]:
a.max(axis=1) #return maximum element of each row

array([ 5, 10])

In [113]:
a.argmax(axis=1)#return index of maximum element in the array

array([4, 4], dtype=int64)

In [116]:
b=a.reshape(5,2)#product of element should be conserved 5*2=2*5

In [117]:
b

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [118]:
b.max(axis=1)

array([ 2,  4,  6,  8, 10])

In [119]:
b.max(axis=0)

array([ 9, 10])

In [120]:
a.reshape(1,2,5)

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]])

In [122]:
n=np.array([[1,2,3,4],[5,6,7,8]])
m=np.array([[9,10,11,12],[13,14,15,16]])

In [126]:
np.concatenate((n,m),axis=None)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [127]:
np.concatenate((n,m),axis=1)

array([[ 1,  2,  3,  4,  9, 10, 11, 12],
       [ 5,  6,  7,  8, 13, 14, 15, 16]])

In [128]:
np.concatenate((n,m),axis=0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [130]:
a=a.reshape(10)

In [131]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [133]:
np.split(a,2)

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]

In [134]:
np.split(a,5)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]

In [137]:
lis=[[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]]

In [142]:
np.split(a,[3,8,10])

[array([1, 2, 3]),
 array([4, 5, 6, 7, 8]),
 array([ 9, 10]),
 array([], dtype=int32)]

In [138]:
lis

[[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]]

In [139]:
arr5=np.array(lis)

In [140]:
arr5

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [144]:
np.split(arr5,3)

[array([[[1, 2],
         [3, 4]]]),
 array([[[5, 6],
         [7, 8]]]),
 array([[[ 9, 10],
         [11, 12]]])]

In [150]:
np.split(arr5,3)

[array([[[1, 2],
         [3, 4]]]),
 array([[[5, 6],
         [7, 8]]]),
 array([[[ 9, 10],
         [11, 12]]])]

In [146]:
arr5.shape

(3, 2, 2)

# changing data type of numpy array

In [9]:
a=np.array([1,2,3,4],dtype=np.int32)
b=np.array([3.0,4.3,5.8,6.7,7.0],dtype=np.float32)
c=np.array([True,False,False,True,True],dtype=np.bool_)

In [10]:
print(a.dtype)
print(b.dtype)
print(c.dtype)

int32
float32
bool


In [11]:
d=np.array([1,2,3,4,5],dtype=np.float64)
d

array([1., 2., 3., 4., 5.])

In [12]:
f=np.array([True,False,True,True,False],dtype=np.int64)
f

array([1, 0, 1, 1, 0], dtype=int64)

In [13]:
e=np.array([1.5,3.0,4.5,6.0,3.5],dtype=np.int64)
e

array([1, 3, 4, 6, 3], dtype=int64)

In [14]:
a.dtype

dtype('int32')

In [18]:
g=a.astype(np.float64)

In [19]:
g

array([1., 2., 3., 4.])

# Numpy-array-operation

In [20]:
a=np.array([[1,2,3,4],[3,4,5,6]])
b=np.array([[5,6,7,8],[9,10,11,12]])

In [21]:
a

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [22]:
b

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [23]:
a+b

array([[ 6,  8, 10, 12],
       [12, 14, 16, 18]])

In [24]:
a-b

array([[-4, -4, -4, -4],
       [-6, -6, -6, -6]])

In [26]:
a/b

array([[0.2       , 0.33333333, 0.42857143, 0.5       ],
       [0.33333333, 0.4       , 0.45454545, 0.5       ]])

In [27]:
a*b

array([[ 5, 12, 21, 32],
       [27, 40, 55, 72]])

In [28]:
np.add(a,b)

array([[ 6,  8, 10, 12],
       [12, 14, 16, 18]])

In [29]:
np.absolute(a-b)

array([[4, 4, 4, 4],
       [6, 6, 6, 6]])

In [30]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [1.73205081, 2.        , 2.23606798, 2.44948974]])

In [31]:
np.square(a)

array([[ 1,  4,  9, 16],
       [ 9, 16, 25, 36]])

In [32]:
np.power(a,b)

array([[          1,          64,        2187,       65536],
       [      19683,     1048576,    48828125, -2118184960]])

In [33]:
np.power(a,3)

array([[  1,   8,  27,  64],
       [ 27,  64, 125, 216]], dtype=int32)

In [36]:
np.log(a)

array([[0.        , 0.69314718, 1.09861229, 1.38629436],
       [1.09861229, 1.38629436, 1.60943791, 1.79175947]])

In [37]:
np.exp(a)

array([[  2.71828183,   7.3890561 ,  20.08553692,  54.59815003],
       [ 20.08553692,  54.59815003, 148.4131591 , 403.42879349]])

In [38]:
np.exp2(b)

array([[  32.,   64.,  128.,  256.],
       [ 512., 1024., 2048., 4096.]])

In [39]:
np.log10(a)

array([[0.        , 0.30103   , 0.47712125, 0.60205999],
       [0.47712125, 0.60205999, 0.69897   , 0.77815125]])

In [40]:
np.log2(b)

array([[2.32192809, 2.5849625 , 2.80735492, 3.        ],
       [3.169925  , 3.32192809, 3.45943162, 3.5849625 ]])

# Matrix Operation

In [50]:
a=np.array([[1,2],[4,5]])
b=np.array([[5,6],[8,9]])

In [51]:
np.dot(a,b)

array([[21, 24],
       [60, 69]])

In [52]:
c=np.array([[1,2,3],[4,5,7]])
d=np.array([[5,6],[8,9]])

In [53]:
np.dot(c,d)

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [54]:
np.dot(d,c)

array([[29, 40, 57],
       [44, 61, 87]])

In [55]:
np.transpose(a)

array([[1, 4],
       [2, 5]])

In [56]:
np.trace(a)

6

In [57]:
np.linalg.det(a)

-2.9999999999999996

In [58]:
np.linalg.inv(a)

array([[-1.66666667,  0.66666667],
       [ 1.33333333, -0.33333333]])

In [59]:
np.linalg.eig(a)

(array([-0.46410162,  6.46410162]),
 array([[-0.80689822, -0.34372377],
        [ 0.59069049, -0.9390708 ]]))

In [69]:
#1*x+2*y=1
#3*x+5*y=2
a=[[1,2],[3,5]]
b=[1,2]

In [63]:
np.linalg.solve(a,b)#to solve equation

array([-1.,  1.])

# broadcasting

In [65]:
a=np.array([[1,2],[3,4]])
b=np.array([10,20])

In [66]:
a

array([[1, 2],
       [3, 4]])

In [67]:
b

array([10, 20])

In [68]:
np.add(a,b)

array([[11, 22],
       [13, 24]])

In [72]:
import time
a=np.random.rand(1000000)
b=np.random.rand(1000000)
start=time.time()
c=a*b
end=time.time()
execution_time=end-start
print('the time taken by python numpy{:6f}seconds'.format(execution_time))
a=list(a)
b=list(b)
c=[]
start=time.time()
for i in range(len(a)):
    c.append(a[i]*b[i])
end=time.time()
forloop_execution_time=end-start
print("time taken by python for loop{:6f}seconds".format(end-start))
print(f'numpy is {int(forloop_execution_time/execution_time)}times faster than python for loop')

the time taken by python numpy0.023763seconds
time taken by python for loop0.443870seconds
numpy is 18times faster than python for loop


In [73]:
#mask-indexing

In [76]:
a=np.array([[1,2],[3,4],[5,6]])
mask=np.array([[True,False],[True,False],[True,False]])

In [77]:
b= a[mask]
print(b)

[1 3 5]


In [78]:
c=np.array([1,2,3,4,5])
mask=np.array([True,False,True,False,True])

In [80]:
b=c[mask]

In [81]:
b

array([1, 3, 5])

In [82]:
a=np.array([[1,2],[3,4],[5,6]])
mask=(a>2)
a[mask]

array([3, 4, 5, 6])