In [5]:
import numpy as np

# creating numpy arrays

# np.array()

In [6]:
list1=[1,2,3,4,5]
array1=np.array(list1)
print(array1)
print(type(array1))
print(array1.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [7]:
lis=[[1,2],[3,4]]
array=np.array(lis)
print(array)
print(type(array))
print(array.ndim)

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
2


# np.zeros()

In [8]:
arrays=np.zeros(5)
print(arrays)

[0. 0. 0. 0. 0.]


In [9]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [11]:
np.zeros((1,2))

array([[0., 0.]])

# np.ones()

In [12]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

# np.full()

In [15]:
np.full(5,2)

array([2, 2, 2, 2, 2])

In [16]:
np.full((2,3),2)

array([[2, 2, 2],
       [2, 2, 2]])

In [17]:
np.full((2,3,4),5)

array([[[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]],

       [[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]]])

# np.arange()

In [18]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [19]:
np.arange(2,6)

array([2, 3, 4, 5])

In [20]:
np.arange(2,10,2)

array([2, 4, 6, 8])

# np.linspace()

In [21]:
np.linspace(1,10,2)

array([ 1., 10.])

In [22]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [23]:
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

In [24]:
np.linspace((2,4),(4,10),5)

array([[ 2. ,  4. ],
       [ 2.5,  5.5],
       [ 3. ,  7. ],
       [ 3.5,  8.5],
       [ 4. , 10. ]])

In [25]:
np.linspace((1,5),(4,10), num=5)

array([[ 1.  ,  5.  ],
       [ 1.75,  6.25],
       [ 2.5 ,  7.5 ],
       [ 3.25,  8.75],
       [ 4.  , 10.  ]])

In [26]:
np.linspace((1,5,6),(4,10,12), num=5)

array([[ 1.  ,  5.  ,  6.  ],
       [ 1.75,  6.25,  7.5 ],
       [ 2.5 ,  7.5 ,  9.  ],
       [ 3.25,  8.75, 10.5 ],
       [ 4.  , 10.  , 12.  ]])

# np.diag()

In [27]:
np.diag([2,3,4])

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 4]])

In [28]:
np.diag([2,3,4],k=1)

array([[0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4],
       [0, 0, 0, 0]])

In [29]:
np.diag([2,3,4],k=-1)

array([[0, 0, 0, 0],
       [2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0]])

# np.eye()

In [30]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
np.eye(5,k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [32]:
np.eye(5,k=1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

# np.identity()

In [33]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# np.random.rand()

In [34]:
np.random.rand(2,3)

array([[0.01527843, 0.53145868, 0.83310673],
       [0.0658693 , 0.15428857, 0.98365568]])

In [35]:
np.random.rand(4,4)

array([[0.0156125 , 0.42423481, 0.4512166 , 0.00094766],
       [0.32468427, 0.13877551, 0.8765478 , 0.00394936],
       [0.6983634 , 0.90719568, 0.81216644, 0.8356085 ],
       [0.60094211, 0.55096476, 0.29874006, 0.03686037]])

In [36]:
np.random.rand(2,3,4)

array([[[0.40442053, 0.79137964, 0.41918023, 0.74591129],
        [0.26898846, 0.71348742, 0.1704369 , 0.74458971],
        [0.48844684, 0.26741472, 0.64190878, 0.946146  ]],

       [[0.69373847, 0.58669311, 0.77995622, 0.1595103 ],
        [0.1148709 , 0.03456348, 0.84324986, 0.90978473],
        [0.99069043, 0.28763948, 0.10297999, 0.81588119]]])

In [37]:
np.random.randint(1,10,(4,4))

array([[4, 5, 5, 4],
       [6, 4, 1, 2],
       [5, 4, 6, 3],
       [9, 1, 4, 5]])

In [38]:
np.random.randint(1,5,(3,3))

array([[4, 2, 3],
       [3, 4, 2],
       [4, 2, 2]])

# Indexing numpy-arrays

In [39]:
arr=np.array([1,2,3,4,5])

In [40]:
arr[3]

4

In [41]:
arr[2]

3

In [42]:
arr

array([1, 2, 3, 4, 5])

In [43]:
list1=[[1,2,3],[4,5,6],[7,8,9]]

In [44]:
arr1=np.array(list1)

In [45]:
arr1[0][1]

2

In [46]:
arr1[0,1]

2

In [47]:
arr2=np.array([[[1,2],[3,4]],[[5,6],[6,7]]])

In [48]:
arr2[0]

array([[1, 2],
       [3, 4]])

In [49]:
arr2[0][1]

array([3, 4])

In [50]:
arr2[1][0][1]

6

# Numpy-array-slicing

In [51]:
li=[1,2,3,4,5]

In [52]:
li[0:4]

[1, 2, 3, 4]

In [53]:
arr3=np.array(li)

In [54]:
arr3[1:4]

array([2, 3, 4])

In [55]:
arrray=[1,2,3,4,5,6,7,8,9,10,11,12]

In [56]:
array=np.array(arrray)

In [57]:
array[3:10:2]

array([ 4,  6,  8, 10])

In [58]:
lis2=[[1,2,3,4,5,6],[7,8,9,10,11,12]]

In [59]:
lis2[0][3:6]

[4, 5, 6]

In [60]:
arr2=np.array(lis2)

In [61]:
arr2[0][3:]

array([4, 5, 6])

In [62]:
arr2[0,3:]

array([4, 5, 6])

In [63]:
arr2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [64]:
arr2[:,1:4]

array([[ 2,  3,  4],
       [ 8,  9, 10]])

In [66]:
arr2[:,1::2]

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [81]:
arr3=[[[1,2,3,4],[5,6,7,8]],[[7,8,9,10],[10,11,12,13]],[[13,14,15,16],[16,17,18,19]]]

arr3

In [82]:
arr3

[[[1, 2, 3, 4], [5, 6, 7, 8]],
 [[7, 8, 9, 10], [10, 11, 12, 13]],
 [[13, 14, 15, 16], [16, 17, 18, 19]]]

In [83]:
arr3[0]

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [84]:
arr4=np.array(arr3)

In [85]:
arr4

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 7,  8,  9, 10],
        [10, 11, 12, 13]],

       [[13, 14, 15, 16],
        [16, 17, 18, 19]]])

In [86]:
arr4[0]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [91]:
arr4[:,:1,1:5]

array([[[ 2,  3,  4]],

       [[ 8,  9, 10]],

       [[14, 15, 16]]])

# Numpy-method and attribute

In [94]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [109]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [95]:
a.shape

(2, 5)

In [97]:
a.dtype

dtype('int32')

In [98]:
a.ndim

2

In [99]:
a.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [100]:
a.sum()

55

In [101]:
a[0].sum()

15

In [102]:
a.max()

10

In [103]:
a[1].max()

10

In [104]:
a[0].max()

5

In [105]:
a.min()

1

In [106]:
a[1].min()

6

In [107]:
a.max(axis=0) #return maximum element of each column

array([ 6,  7,  8,  9, 10])

In [108]:
a.max(axis=1) #return maximum element of each row

array([ 5, 10])

In [113]:
a.argmax(axis=1)#return index of maximum element in the array

array([4, 4], dtype=int64)

In [116]:
b=a.reshape(5,2)#product of element should be conserved 5*2=2*5

In [117]:
b

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [118]:
b.max(axis=1)

array([ 2,  4,  6,  8, 10])

In [119]:
b.max(axis=0)

array([ 9, 10])

In [120]:
a.reshape(1,2,5)

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]])

In [122]:
n=np.array([[1,2,3,4],[5,6,7,8]])
m=np.array([[9,10,11,12],[13,14,15,16]])

In [126]:
np.concatenate((n,m),axis=None)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [127]:
np.concatenate((n,m),axis=1)

array([[ 1,  2,  3,  4,  9, 10, 11, 12],
       [ 5,  6,  7,  8, 13, 14, 15, 16]])

In [128]:
np.concatenate((n,m),axis=0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [130]:
a=a.reshape(10)

In [131]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [133]:
np.split(a,2)

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]

In [134]:
np.split(a,5)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]

In [137]:
lis=[[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]]

In [142]:
np.split(a,[3,8,10])

[array([1, 2, 3]),
 array([4, 5, 6, 7, 8]),
 array([ 9, 10]),
 array([], dtype=int32)]

In [138]:
lis

[[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]]

In [139]:
arr5=np.array(lis)

In [140]:
arr5

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [144]:
np.split(arr5,3)

[array([[[1, 2],
         [3, 4]]]),
 array([[[5, 6],
         [7, 8]]]),
 array([[[ 9, 10],
         [11, 12]]])]

In [150]:
np.split(arr5,3)

[array([[[1, 2],
         [3, 4]]]),
 array([[[5, 6],
         [7, 8]]]),
 array([[[ 9, 10],
         [11, 12]]])]

In [146]:
arr5.shape

(3, 2, 2)