In [1]:
import numpy as np

# creating numpy arrays

# np.array()

In [4]:
list1=[1,2,3,4,5]
array1=np.array(list1)
print(array1)
print(type(array1))
print(array1.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [5]:
lis=[[1,2],[3,4]]
array=np.array(lis)
print(array)
print(type(array))
print(array.ndim)

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
2


# np.zeros()

In [6]:
arrays=np.zeros(5)
print(arrays)

[0. 0. 0. 0. 0.]


In [8]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [9]:
np.zeros((1,2))

array([[0., 0.]])

# np.ones()

In [12]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

# np.full()

In [15]:
np.full(5,2)

array([2, 2, 2, 2, 2])

In [16]:
np.full((2,3),2)

array([[2, 2, 2],
       [2, 2, 2]])

In [17]:
np.full((2,3,4),5)

array([[[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]],

       [[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]]])

# np.arange()

In [18]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [19]:
np.arange(2,6)

array([2, 3, 4, 5])

In [20]:
np.arange(2,10,2)

array([2, 4, 6, 8])

# np.linspace()

In [21]:
np.linspace(1,10,2)

array([ 1., 10.])

In [22]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [23]:
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

In [24]:
np.linspace((2,4),(4,10),5)

array([[ 2. ,  4. ],
       [ 2.5,  5.5],
       [ 3. ,  7. ],
       [ 3.5,  8.5],
       [ 4. , 10. ]])

In [26]:
np.linspace((1,5),(4,10), num=5)

array([[ 1.  ,  5.  ],
       [ 1.75,  6.25],
       [ 2.5 ,  7.5 ],
       [ 3.25,  8.75],
       [ 4.  , 10.  ]])

In [27]:
np.linspace((1,5,6),(4,10,12), num=5)

array([[ 1.  ,  5.  ,  6.  ],
       [ 1.75,  6.25,  7.5 ],
       [ 2.5 ,  7.5 ,  9.  ],
       [ 3.25,  8.75, 10.5 ],
       [ 4.  , 10.  , 12.  ]])

# np.diag()

In [29]:
np.diag([2,3,4])

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 4]])

In [30]:
np.diag([2,3,4],k=1)

array([[0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4],
       [0, 0, 0, 0]])

In [32]:
np.diag([2,3,4],k=-1)

array([[0, 0, 0, 0],
       [2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0]])

# np.eye()

In [33]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
np.eye(5,k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [35]:
np.eye(5,k=1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

# np.identity()

In [36]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# np.random.rand()

In [37]:
np.random.rand(2,3)

array([[0.52094859, 0.20091962, 0.02635734],
       [0.42101642, 0.1471216 , 0.40416553]])

In [39]:
np.random.rand(4,4)

array([[0.1977254 , 0.15073396, 0.96457107, 0.52088418],
       [0.00273405, 0.70084427, 0.80623955, 0.9041379 ],
       [0.02067206, 0.98742922, 0.73972459, 0.91944435],
       [0.78713241, 0.79290837, 0.55583116, 0.44107925]])

In [40]:
np.random.rand(2,3,4)

array([[[0.05299545, 0.30695748, 0.15988588, 0.48746831],
        [0.16870342, 0.68564609, 0.4774121 , 0.819046  ],
        [0.33848848, 0.21551119, 0.6543506 , 0.31622937]],

       [[0.20899473, 0.7088778 , 0.88719642, 0.47934943],
        [0.55152413, 0.46035799, 0.94367913, 0.34863638],
        [0.66596693, 0.70704454, 0.63043779, 0.72281475]]])

In [41]:
np.random.randint(1,10,(4,4))

array([[9, 7, 8, 2],
       [3, 4, 5, 6],
       [1, 9, 5, 4],
       [6, 2, 4, 2]])

In [49]:
np.random.randint(1,5,(3,3))

array([[1, 1, 3],
       [1, 2, 2],
       [4, 1, 2]])

# Indexing numpy-arrays

In [51]:
arr=np.array([1,2,3,4,5])

In [52]:
arr[3]

4

In [53]:
arr[2]

3

In [54]:
arr

array([1, 2, 3, 4, 5])

In [56]:
list1=[[1,2,3],[4,5,6],[7,8,9]]

In [57]:
arr1=np.array(list1)

In [58]:
arr1[0][1]

2

In [59]:
arr1[0,1]

2

In [61]:
arr2=np.array([[[1,2],[3,4]],[[5,6],[6,7]]])

In [62]:
arr2[0]

array([[1, 2],
       [3, 4]])

In [63]:
arr2[0][1]

array([3, 4])

In [64]:
arr2[1][0][1]

6